# This workflow will install Python dependencies, run tests, and execute the script on a schedule.
# Manual execution is also enabled.

name: Extract GIRA EMEL Availability

on:
    schedule:
      - cron: "*/5 * * * *"  # Runs at 0, 5, 10, etc.
      - cron: "1-59/5 * * * *"  # Runs at 1, 6, 11, etc.
      - cron: "2-59/5 * * * *"  # Runs at 2, 7, 12, etc.
      - cron: "3-59/5 * * * *"  # Runs at 3, 8, 13, etc.
      - cron: "4-59/5 * * * *"  # Runs at 4, 9, 14, etc.
    workflow_dispatch:  # Enables manual execution from GitHub Actions UI

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: |
        python 01.Get_CARRIS_RT.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update GIRA
        branch: ${{ github.head_ref }}
